services:
  postgres:
    image: postgres:latest
    container_name: yuri_postgres
    environment:
      POSTGRES_DB: "yuri_chat"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5434:5432"

  s3:
    image: minio/minio:latest
    container_name: yuri_s3
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
